import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SINGHAAR Fashion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-pink-100`}>
        <div className='max-w-[90%] mx-auto'>
          <Providers>
        <Navbar/>
        {children}
        <Footer/>
        </Providers>
        </div>
        </body>
    </html>
  );
};
