import {Product} from "./type";

export const products:Product[] = [
    {
        id:1,
        title:"Denim-Blue-Faded-Shirt",
        image:["/assets/pictures/Denim Blue faded shirt.jpg" ],
        slug: "Denim-Blue-Faded--Shirt",
        price:25,
        discount:40,
        category:"tops",
        description:
        "Best quality Denim Blue Faded Shirt for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["S","M","L","XL"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:2,
        title:"Plain-Green-Top",
        image:["/assets/pictures/bestselling1.jpg" ],
        slug: "Plain-Green-Top",
        price:20,
        discount:40,
        category:"tops",
        description:
        "Best quality Plain Green tops for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["S","M","L","XL"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:3,
        title:"Printed-Top",
        image:["/assets/pictures/top.jpg"],
        slug: "Printed-Top",
        price:25,
        discount:40,
        category:"tops",
        description:
        "Best quality Printed for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["S","M","L","XL"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:4,
        title:"Black-Humming-Bird-Teashirt",
        image:["/assets/pictures/teashirt1.jpg", "/assets/pictures/teashirt.jpg", "/assets/pictures/bestselling1.jpg", "/assets/pictures/top2.png","/assets/pictures/top.jpg", "/assets/pictures/Denim Blue faded shirt.jpg" ],
        slug: "Black-HummingBird-Teashirt",
        price:12,
        discount:0,
        category:"tops",
        description:
        "Best quality Black Humming Bird TeaShirt for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["S","M","L","XL"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:5,
        title:"Plain-Black-TeaShirt",
        image:["/assets/pictures/teashirt.jpg" ],
        slug: "Plain-Black-TeaShirt",
        price:12,
        discount:0,
        category:"tops",
        description:
        "Best quality tops for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["S","M","L","XL"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    
    {
        id:7,
        title:"Brown-Bag",
        image:["/assets/pictures/maroonbag1.jpg"],
        slug: "Brown-Bag",
        price:150,
        discount:50,
        category:"bags",
        description:
        "Best quality Bags for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["Standard"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:8,
        title:"Brown-Leather-Bag",
        image:["/assets/pictures/bags.jpg"],
        slug: "Brown-Leather-Bag",
        price:150,
        discount:50,
        category:"bags",
        description:
        "Best quality Brown Leather Bag for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["Standard"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:9,
        title:"Pink-Jenz-Pant",
        image:["/assets/pictures/pants1.jpg"],
        slug: "Pink-Jenz-Pant",
        price:15,
        discount:0,
        category:"pants",
        description:
        "Best quality Pink Jenz Pants for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["S","M","L","XL"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:10,
        title:"Camel-Pant",
        image:["/assets/pictures/pants.jpg"],
        slug: "Camel-Pant",
        price:15,
        discount:0,
        category:"pants",
        description:
        "Best quality Camel Pant for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["S","M","L","XL"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:11,
        title:"Black-Sneakers",
        image:["/assets/pictures/sneakers1.jpg"],
        slug: "Black-Sneakers",
        price:120,
        discount:30,
        category:"shoes",
        description:
        "Top-Notch Black Sneakers for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["6","7","8","9","10"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:12,
        title:"Red-Sneakers",
        image:["/assets/pictures/shoes.jpg"],
        slug: "Red-Sneakers",
        price:120,
        discount:30,
        category:"shoes",
        description:
        "Top-Notch Red Sneakers for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["6","7","8","9","10"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
    {
        id:13,
        title:"Accessories",
        image:["/assets/pictures/accessories.jpg"],
        slug: "Accesories",
        price:25,
        discount:10,
        category:"accessories",
        description:
        "Top-Notch Accessories & Jewellery for women, Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident et consectetur natus aperiam libero cupiditate modi repellendus dolores! Quidem laborum magnam minima excepturi adipisci quod aspernatur, odit perferendis non officia! ",
        size:["Standard"],
        color:["#ffffff", "#000000", "#e60000"],
        qty:1,
    },
];